theme: jekyll-theme-minimal

title: Sohag Mahamud
author:
  name: Md. Mahamudur Rahman Sohag
  email: sohagmahamud@live.com

google_analytics: 

description: >- # this means to ignore newlines until "baseurl:"
  AI/ML Researcher | Software Engineer | Innovator

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sohagmahamud.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: sohagmahamudpro
linkedin_username: sohagmahamud

gem "jekyll-seo-tag"
plugins:
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

minima:
  nav:
    - "Home" | "/"
    - "AI Research" | "/ai-research/"
    - "Projects" | "/projects/"
    - "Blog" | "/blog/"
    - "About" | "/about/"